language: objective-c
osx_image: xcode8
xcode_workspace: TezButtonExample.xcodeproj
xcode_scheme: TezButtonExample
-xcode_sdk: iphonesimulator10.0		

script:
- set -o pipefail && xcodebuild test -project TezButtonExample.xcodeproj -scheme TezButtonExample | xcpretty
- pod lib lint
