language: objective-c
osx_image: xcode8.3
xcode_workspace: TezButtonExample.xcodeproj
xcode_scheme: TezButtonExample

script:
- set -o pipefail && xcodebuild test -project TezButtonExample.xcodeproj -scheme TezButtonExample -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
